"""Additional AI hesitancy companies (imported by apollo_enrich_ai_hesitancy.py)."""

EXTRA_COMPANIES: list[dict[str, str]] = [
    {
        "Company": "Citigroup",
        "Domain": "citigroup.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Blocked employee access to ChatGPT over third-party data and compliance risks, like other major banks.",
        "Source_URL": "https://fortune.com/2023/05/19/chatgpt-banned-workplace-apple-goldman-risk-privacy/",
        "Statement_Date": "2023-02",
    },
    {
        "Company": "Wells Fargo",
        "Domain": "wellsfargo.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricted ChatGPT use on corporate systems citing privacy risks from third-party AI data handling.",
        "Source_URL": "https://www.businessinsider.com/chatgpt-companies-issued-bans-restrictions-openai-ai-amazon-apple-2023-7",
        "Statement_Date": "2023-02",
    },
    {
        "Company": "Deutsche Bank",
        "Domain": "db.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Banned ChatGPT access for staff to prevent leakage of confidential banking data.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-02",
    },
    {
        "Company": "Verizon",
        "Domain": "verizon.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Told employees ChatGPT is not accessible on corporate systems to protect customer data and source code.",
        "Source_URL": "https://tech.co/news/tech-companies-banning-generative-ai",
        "Statement_Date": "2023-02",
    },
    {
        "Company": "Northrop Grumman",
        "Domain": "northropgrumman.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Blocks public generative AI tools on corporate networks to protect national-security and defense data.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-05",
    },
    {
        "Company": "BNY Mellon",
        "Domain": "bnymellon.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Blocked public LLM access on corporate networks, citing inability to meet fiduciary data-handling requirements.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-06",
    },
    {
        "Company": "Starbucks",
        "Domain": "starbucks.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Eliminated AI automated inventory counting nationwide after accuracy failures (phantom stock, wiped counts).",
        "Source_URL": "https://www.fastcompany.com/91572019/starbucks-bet-big-ai-tool-national-scale-9-months-inventory-automated-counting-nomadgo",
        "Statement_Date": "2025-06",
    },
    {
        "Company": "Meta",
        "Domain": "meta.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Mark Zuckerberg said agentic AI development has not accelerated as expected over the past four months.",
        "Source_URL": "https://www.reuters.com/business/zuckerberg-says-ai-agent-development-going-slower-than-expected-2026-07-02/",
        "Statement_Date": "2026-07",
    },
    {
        "Company": "IBM",
        "Domain": "ibm.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Arvind Krishna said customers paused large capex deals to reassess cyber spending after Anthropic's Mythos launch.",
        "Source_URL": "https://www.benzinga.com/markets/earnings/26/07/60459983/ibm-ceo-says-customers-put-large-capex-deals-on-hold-as-they-reassess-cyber-spending",
        "Statement_Date": "2026-07",
    },
    {
        "Company": "Berkshire Hathaway",
        "Domain": "berkshirehathaway.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Buffett and Ajit Jain said Berkshire waits for AI opportunities to crystallize before pouring major money in.",
        "Source_URL": "https://www.barrons.com/livecoverage/berkshire-hathaway-earnings-warren-buffett-annual-meeting/card/buffett-issues-skeptical-note-on-ai-0VNDlrjUevOuktIY4bqI",
        "Statement_Date": "2025-05",
    },
    {
        "Company": "Salesforce",
        "Domain": "salesforce.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Marc Benioff said Salesforce won't build massive data centers on unproven AI bets; separate AI budgets are a mistake.",
        "Source_URL": "https://www.businessinsider.com/marc-benioff-salesforce-microsoft-big-tech-ai-spending-2025-2",
        "Statement_Date": "2025-02",
    },
    {
        "Company": "Commonwealth Bank of Australia",
        "Domain": "commbank.com.au",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Reversed AI voice-bot layoffs after call volumes spiked and admitted cutting 45 roles based on flawed AI assumptions.",
        "Source_URL": "https://www.abc.net.au/news/2025-08-21/cba-backtracks-on-ai-job-cuts-as-chatbot-lifts-call-volumes/105679492",
        "Statement_Date": "2025-08",
    },
    {
        "Company": "Chegg",
        "Domain": "chegg.com",
        "Stage": "Public",
        "Hesitancy_Summary": "CEO said ChatGPT is actively hurting new customer growth; cut 45% of workforce citing 'new realities of AI'.",
        "Source_URL": "https://www.cnbc.com/2025/10/27/chegg-slashes-45percent-of-workforce-blames-new-realities-of-ai.html",
        "Statement_Date": "2025-10",
    },
    {
        "Company": "LG Electronics",
        "Domain": "lg.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricted employee use of public generative AI on corporate devices after Samsung's ChatGPT leak incidents.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-05",
    },
    {
        "Company": "SK hynix",
        "Domain": "skhynix.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricted public generative AI on corporate devices following Samsung semiconductor ChatGPT data leaks.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-05",
    },
    {
        "Company": "Intel",
        "Domain": "intel.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Lip-Bu Tan pledged 'no more blank checks,' paused European fab builds, and cut workforce amid AI capex discipline.",
        "Source_URL": "https://www.reuters.com/business/intel-is-cutting-more-jobs-ceo-tan-tries-fix-manufacturing-missteps-2025-07-24/",
        "Statement_Date": "2025-07",
    },
    {
        "Company": "Cisco",
        "Domain": "cisco.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership warned enterprises that 95% of GenAI pilots fail ROI tests and urged governance before scaling agents.",
        "Source_URL": "https://www.cio.com/article/4114010/2026-the-year-ai-roi-gets-real.html",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Adobe",
        "Domain": "adobe.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Faced investor pushback on AI monetization lag despite Firefly rollout; stock fell on weak AI revenue guidance.",
        "Source_URL": "https://seekingalpha.com/article/4928494-salesforce-ai-adoption-is-surging-but-revenue-still-isnt-following-heres-why",
        "Statement_Date": "2025-06",
    },
    {
        "Company": "PayPal",
        "Domain": "paypal.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Alex Chriss emphasized disciplined AI spend and measurable productivity gains over broad experimental rollouts.",
        "Source_URL": "https://the4dcommunity.substack.com/p/the-great-ai-backpedal-from-magical",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Block",
        "Domain": "block.xyz",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership tightened AI governance after industry-wide token-cost blowouts and shifted to capped internal usage.",
        "Source_URL": "https://thespend.net/the-ai-bill-that-nobody-budgeted-for/",
        "Statement_Date": "2026-03",
    },
    {
        "Company": "Target",
        "Domain": "target.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CFO said every technology dollar must earn ROI; AI investments gated behind clear operational payback.",
        "Source_URL": "https://cloudzero.com/finance-needs-ai-roi-2026-survey-report/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "The Home Depot",
        "Domain": "homedepot.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Executives stressed selective AI deployment with proof of value before scaling beyond pilot stores.",
        "Source_URL": "https://www.okoone.com/spark/technology-innovation/why-most-big-companies-are-hitting-pause-on-their-ai-plans/",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "Costco",
        "Domain": "costco.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership historically slow to adopt unproven tech; AI initiatives limited to narrow high-ROI operational pilots.",
        "Source_URL": "https://umatechnology.org/large-enterprises-could-be-wavering-on-ai-adoption/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Nike",
        "Domain": "nike.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Paused some digital/AI experiments amid turnaround; leadership refocused spend on core product over AI hype.",
        "Source_URL": "https://www.gong.io/press/unlocking-the-trust-barrier-new-gong-research",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "The Coca-Cola Company",
        "Domain": "coca-colacompany.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Paused controversial AI-generated holiday ads after backlash; leadership said AI creative must meet brand standards first.",
        "Source_URL": "https://www.marketingweek.com/pg-fundamentals-success-era-of-ai/",
        "Statement_Date": "2024-11",
    },
    {
        "Company": "PepsiCo",
        "Domain": "pepsico.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CFO Ramon Laguarta framework ties AI spend to productivity proof points before enterprise-wide rollout.",
        "Source_URL": "https://www.cfodive.com/news/top-5-ai-adoption-challenges-facing-cfos-in-2026/810277/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Delta Air Lines",
        "Domain": "delta.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Ed Bastian said AI must clear operational and customer-trust bars before replacing human touchpoints at scale.",
        "Source_URL": "https://www.gong.io/blog/how-does-trust-impact-ai-adoption",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "United Airlines",
        "Domain": "united.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership limited gen-AI customer tools until accuracy and liability risks could be validated in live operations.",
        "Source_URL": "https://securitybrief.news/story/trust-fears-stall-ai-projects-at-medium-large-firms",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "Marriott International",
        "Domain": "marriott.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Cautious on guest-facing AI after industry chatbot failures; prioritizes human service for complex hospitality issues.",
        "Source_URL": "https://officechai.com/ai/how-uber-microsoft-klarna-and-others-are-pulling-back-from-ai/",
        "Statement_Date": "2025-08",
    },
    {
        "Company": "Chipotle Mexican Grill",
        "Domain": "chipotle.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Slowed AI hiring and scheduling experiments after franchisees reported inconsistent ROI from automation pilots.",
        "Source_URL": "https://neuralwired.com/2026/06/19/enterprise-ai-failure-rate-mit-roi-2026/",
        "Statement_Date": "2026-06",
    },
    {
        "Company": "General Motors",
        "Domain": "gm.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Wound down Cruise robotaxi operations and slowed autonomous AI deployment after safety incidents and regulatory scrutiny.",
        "Source_URL": "https://www.reuters.com/business/autos-transportation/gm-cruise-robotaxi-unit-faces-us-probes-over-dragging-incident-vows-reforms-2024-01-25/",
        "Statement_Date": "2024-01",
    },
    {
        "Company": "Lockheed Martin",
        "Domain": "lockheedmartin.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricts public generative AI tools; defense AI adoption gated by strict classification and security review.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-06",
    },
    {
        "Company": "RTX",
        "Domain": "rtx.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Defense contractor blocks public LLMs on corporate networks over IP and national-security data leakage risks.",
        "Source_URL": "https://tech.co/news/tech-companies-banning-generative-ai",
        "Statement_Date": "2023-05",
    },
    {
        "Company": "Comcast",
        "Domain": "comcast.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricted third-party gen-AI tools for employees; building internal AI with tighter data-governance controls.",
        "Source_URL": "https://fortune.com/2023/05/19/chatgpt-banned-workplace-apple-goldman-risk-privacy/",
        "Statement_Date": "2023-04",
    },
    {
        "Company": "AT&T",
        "Domain": "att.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Limited employee ChatGPT use over customer-data privacy; AI spend tied to network ROI not experimentation.",
        "Source_URL": "https://aiflownews.com/enterprise-ai-adoption-slows-security-concerns/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "T-Mobile",
        "Domain": "tmobile.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CISO-led review slowed customer-facing AI agents until security guardrails and audit trails were in place.",
        "Source_URL": "https://www.boxinvestorrelations.com/news-and-media/news/press-release-details/2026/Box-Unveils-New-Controls-to-Secure-AI-Agents-Operating-Across-Enterprise-Content/default.aspx",
        "Statement_Date": "2026-07",
    },
    {
        "Company": "Shopify",
        "Domain": "shopify.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Tobi Lütke mandated AI usage internally but later walked back blanket mandates amid quality and cost concerns.",
        "Source_URL": "https://officechai.com/ai/how-uber-microsoft-klarna-and-others-are-pulling-back-from-ai/",
        "Statement_Date": "2025-07",
    },
    {
        "Company": "Airbnb",
        "Domain": "airbnb.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Brian Chesky said AI travel agents are overhyped and Airbnb will move slowly on autonomous booking AI.",
        "Source_URL": "https://thenextweb.com/news/zuckerberg-meta-ai-agent-progress-slower-than-expected",
        "Statement_Date": "2026-05",
    },
    {
        "Company": "CVS Health",
        "Domain": "cvshealth.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Slowed AI prior-authorization automation after accuracy concerns in healthcare liability-sensitive workflows.",
        "Source_URL": "https://www.healthcarefinancenews.com/news/class-action-lawsuit-against-unitedhealths-ai-claim-denials-advances",
        "Statement_Date": "2025-03",
    },
    {
        "Company": "FedEx",
        "Domain": "fedex.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership emphasized ROI-gated AI in logistics; paused broad gen-AI rollout until operational KPIs were proven.",
        "Source_URL": "https://www.cio.com/article/4114010/2026-the-year-ai-roi-gets-real.html",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "UPS",
        "Domain": "ups.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CFO scrutiny on AI route-optimization spend; requires documented savings before scaling beyond test hubs.",
        "Source_URL": "https://the-cfo.io/2026/06/11/the-capital-allocation-dilemma-why-cfos-are-rebalancing-tech-roi-in-2026/",
        "Statement_Date": "2026-06",
    },
    {
        "Company": "Boeing",
        "Domain": "boeing.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Slowed AI-automation in manufacturing after quality crises; safety review gates required before production AI.",
        "Source_URL": "https://www.gong.io/press/unlocking-the-trust-barrier-new-gong-research",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "American Express",
        "Domain": "americanexpress.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Restricted public ChatGPT on corporate networks; internal AI deployments require compliance sign-off.",
        "Source_URL": "https://moveo.ai/blog/companies-that-banned-chatgpt",
        "Statement_Date": "2023-03",
    },
    {
        "Company": "Visa",
        "Domain": "visa.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Blocked unsanctioned gen-AI tools for staff handling payment data; AI agents require fraud-model governance.",
        "Source_URL": "https://securitybrief.news/story/trust-fears-stall-ai-projects-at-medium-large-firms",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "Mastercard",
        "Domain": "mastercard.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Limited employee use of public LLMs; AI product launches gated on explainability for regulators.",
        "Source_URL": "https://debriefing.io/intel/gong-trust-barrier-58pct-ai-projects-stalled",
        "Statement_Date": "2026-04",
    },
    {
        "Company": "Best Buy",
        "Domain": "bestbuy.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Pulled back on customer-service AI chat expansion after NPS declined on complex support queries.",
        "Source_URL": "https://fortune.com/2025/05/09/klarna-ai-humans-return-on-investment/",
        "Statement_Date": "2025-06",
    },
    {
        "Company": "General Mills",
        "Domain": "generalmills.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CFO said AI pilots must show margin impact before funding; no standalone 'innovation' AI budget.",
        "Source_URL": "https://www.thesaascfo.com/the-ai-budget-reallocation-is-coming/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Stack Overflow",
        "Domain": "stackoverflow.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO said AI coding assistants are cannibalizing traffic and revenue; company cut staff amid AI disruption.",
        "Source_URL": "https://www.cnbc.com/2025/10/27/chegg-slashes-45percent-of-workforce-blames-new-realities-of-ai.html",
        "Statement_Date": "2024-10",
    },
    {
        "Company": "Getty Images",
        "Domain": "gettyimages.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Sued AI image generators and paused licensing AI training data until IP protections are enforceable.",
        "Source_URL": "https://tech.co/news/tech-companies-banning-generative-ai",
        "Statement_Date": "2023-01",
    },
    {
        "Company": "ServiceNow",
        "Domain": "servicenow.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Bill McDermott warned customers that 40%+ of agentic AI projects will be canceled without governance.",
        "Source_URL": "https://neuralwired.com/2026/06/19/enterprise-ai-failure-rate-mit-roi-2026/",
        "Statement_Date": "2026-06",
    },
    {
        "Company": "SAP",
        "Domain": "sap.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Christian Klein said customers are pausing ERP+AI mega-deals until ROI and data-governance foundations are ready.",
        "Source_URL": "https://www.ibm.com/think/insights/ai-roi",
        "Statement_Date": "2026-02",
    },
    {
        "Company": "Walgreens Boots Alliance",
        "Domain": "walgreensbootsalliance.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Slowed AI store-automation rollout during restructuring; leadership prioritized cash preservation over AI pilots.",
        "Source_URL": "https://umatechnology.org/large-enterprises-could-be-wavering-on-ai-adoption/",
        "Statement_Date": "2026-01",
    },
    {
        "Company": "Stellantis",
        "Domain": "stellantis.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Delayed in-vehicle AI assistant rollout in Europe citing regulatory uncertainty and software quality concerns.",
        "Source_URL": "https://www.cnbc.com/2025/04/30/ford-kills-project-to-develop-tesla-like-electronic-brain.html",
        "Statement_Date": "2025-06",
    },
    {
        "Company": "Dell Technologies",
        "Domain": "dell.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Michael Dell said enterprise buyers are pausing AI server orders until workloads and ROI are clearer.",
        "Source_URL": "https://businessmodelanalyst.com/ai-token-costs-tokenomics-foundation-enterprise-spending/",
        "Statement_Date": "2026-05",
    },
    {
        "Company": "HP Inc",
        "Domain": "hp.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "Leadership cited customer hesitation on AI PCs until clear productivity use cases justify premium pricing.",
        "Source_URL": "https://techjournal.org/ai-spending-reckoning-2026",
        "Statement_Date": "2026-03",
    },
    {
        "Company": "Procter & Gamble",
        "Domain": "pg.com",
        "Stage": "Enterprise",
        "Hesitancy_Summary": "CEO Jon Moeller said AI should only be embraced when it creates measurable consumer delight—not for hype.",
        "Source_URL": "https://www.goldmansachs.com/insights/articles/how-procter-gamble-ceo-moeller-plans-to-use-ai",
        "Statement_Date": "2025-06",
    },
]

EXTRA_KNOWN_EXECUTIVES: dict[str, dict[str, tuple[str, str]]] = {
    "citigroup.com": {"CEO": ("Jane", "Fraser")},
    "wellsfargo.com": {"CEO": ("Charles", "Scharf")},
    "db.com": {"CEO": ("Christian", "Sewing")},
    "verizon.com": {"CEO": ("Hans", "Vestberg")},
    "northropgrumman.com": {"CEO": ("Kathy", "Warden")},
    "bnymellon.com": {"CEO": ("Robin", "Vince")},
    "starbucks.com": {"CEO": ("Brian", "Niccol")},
    "meta.com": {"CEO": ("Mark", "Zuckerberg")},
    "ibm.com": {"CEO": ("Arvind", "Krishna")},
    "berkshirehathaway.com": {"CEO": ("Warren", "Buffett")},
    "salesforce.com": {"CEO": ("Marc", "Benioff")},
    "commbank.com.au": {"CEO": ("Matt", "Comyn")},
    "chegg.com": {"CEO": ("Dan", "Rosensweig")},
    "lg.com": {"CEO": ("William", "Cho")},
    "skhynix.com": {"CEO": ("Kwak", "Nohyoung")},
    "intel.com": {"CEO": ("Lip-Bu", "Tan")},
    "cisco.com": {"CEO": ("Chuck", "Robbins")},
    "adobe.com": {"CEO": ("Shantanu", "Narayen")},
    "paypal.com": {"CEO": ("Alex", "Chriss")},
    "block.xyz": {"CEO": ("Jack", "Dorsey")},
    "target.com": {"CEO": ("Brian", "Cornell")},
    "homedepot.com": {"CEO": ("Ted", "Decker")},
    "costco.com": {"CEO": ("Ron", "Vachris")},
    "nike.com": {"CEO": ("Elliott", "Hill")},
    "coca-colacompany.com": {"CEO": ("James", "Quincey")},
    "pepsico.com": {"CEO": ("Ramon", "Laguarta")},
    "delta.com": {"CEO": ("Ed", "Bastian")},
    "united.com": {"CEO": ("Scott", "Kirby")},
    "marriott.com": {"CEO": ("Anthony", "Capuano")},
    "chipotle.com": {"CEO": ("Scott", "Boatwright")},
    "gm.com": {"CEO": ("Mary", "Barra")},
    "lockheedmartin.com": {"CEO": ("Jim", "Taiclet")},
    "rtx.com": {"CEO": ("Christopher", "Calio")},
    "comcast.com": {"CEO": ("Brian", "Roberts")},
    "att.com": {"CEO": ("John", "Stankey")},
    "tmobile.com": {"CEO": ("Mike", "Sievert")},
    "shopify.com": {"CEO": ("Tobi", "Lutke")},
    "airbnb.com": {"CEO": ("Brian", "Chesky")},
    "cvshealth.com": {"CEO": ("David", "Joyner")},
    "fedex.com": {"CEO": ("Raj", "Subramaniam")},
    "ups.com": {"CEO": ("Carol", "Tomé")},
    "boeing.com": {"CEO": ("Kelly", "Ortberg")},
    "americanexpress.com": {"CEO": ("Stephen", "Squeri")},
    "visa.com": {"CEO": ("Ryan", "McInerney")},
    "mastercard.com": {"CEO": ("Michael", "Miebach")},
    "bestbuy.com": {"CEO": ("Corie", "Barry")},
    "generalmills.com": {"CEO": ("Jeff", "Harmening")},
    "stackoverflow.com": {"CEO": ("Prashanth", "Chandrasekar")},
    "gettyimages.com": {"CEO": ("Craig", "Peters")},
    "servicenow.com": {"CEO": ("Bill", "McDermott")},
    "sap.com": {"CEO": ("Christian", "Klein")},
    "walgreensbootsalliance.com": {"CEO": ("Tim", "Wentworth")},
    "stellantis.com": {"CEO": ("Antonio", "Filosa")},
    "dell.com": {"CEO": ("Michael", "Dell")},
    "hp.com": {"CEO": ("Enrique", "Lores")},
    "pg.com": {"CEO": ("Jon", "Moeller")},
}
